ToDoList/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoList.Models
{
    public class ToDo
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool IsDone { get; set; }
        public bool IsDone1 { get; set; }
        public bool IsDone2 { get; set; }
        public int RowNo { get; set; }
        public bool IsAdmin { get; set; }

        public virtual ApplicationUser User { get; set; }

    }
}

ToDoList/Controllers/ToDoesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;
 

namespace ToDoList.Controllers
{
    public class ToDoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ToDo todo = new ToDo();
        


        // GET: ToDoes
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UpdateItem(string itemIds)
        {
            int counta = 1;
            List<int> itemIdList = new List<int>();
            itemIdList = itemIds.Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();
            foreach(var itemId in itemIdList)
            {
                try
                {
                    ToDo item = db.ToDos.Where(x => x.Id == itemId).FirstOrDefault();
                    item.RowNo = counta;
                    db.ToDos.AddOrUpdate(item);
                    db.SaveChanges();
                }
                catch(Exception)
                {
                    continue;
                }
                counta++;
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private IEnumerable<ToDo> GetMyToDoes()
        {
            string currentUserId = User.Identity.GetUserId();

            if (todo.IsAdmin) {
                IEnumerable<ToDo> myToDoes2 = db.ToDos.ToList();
                ViewBag.Percent = Math.Round(100f * ((float)myToDoes2.Count(x => x.IsDone2 == true) / (float)myToDoes2.Count()));

                return myToDoes2;
            }
            else {
                ApplicationUser currentUser = db.Users.FirstOrDefault
                    (x => x.Id == currentUserId);

                IEnumerable<ToDo> myToDoes = db.ToDos.ToList();
                ViewBag.Percent = Math.Round(100f * ((float)myToDoes.Count(x => x.IsDone2 == true) / (float)myToDoes.Count()));

                return myToDoes;
            }
            

            //return View(db.ToDos.ToList());
        }

        public ActionResult BuildToDoTable()
        {
            return PartialView("_ToDoTable", GetMyToDoes());
        }

        // GET: ToDoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // GET: ToDoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToDoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,IsDone")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault
                    (x => x.Id == currentUserId);
                toDo.User = currentUser;
                db.ToDos.Add(toDo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(toDo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id,Description")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault
                    (x => x.Id == currentUserId);
                toDo.User = currentUser;
                toDo.IsDone = false;
                toDo.IsDone1 = false;
                toDo.IsDone2 = false;
                toDo.IsAdmin = false;
                db.ToDos.Add(toDo);
                db.SaveChanges();

            }

            return PartialView("_ToDoTable", GetMyToDoes());
        }



        // GET: ToDoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);

            if (toDo == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);

            if (toDo.User != currentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(toDo);
        }

        // POST: ToDoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,IsDone")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toDo);
        }

        [HttpPost]
        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.IsDone = value;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_ToDoTable", GetMyToDoes());
            }
        }

        public ActionResult AJAXEdit1(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.IsDone1 = value;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_ToDoTable", GetMyToDoes());
            }
        }

        public ActionResult AJAXEdit2(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.IsDone2 = value;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_ToDoTable", GetMyToDoes());
            }
        }

        public ActionResult AJAXEditAdmin(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.IsAdmin = true;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_ToDoTable", GetMyToDoes());
            }
        }

        // GET: ToDoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // POST: ToDoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToDo toDo = db.ToDos.Find(id);
            db.ToDos.Remove(toDo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToDoList/Views/ToDoes/Create.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoes/Delete.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoList/Views/ToDoes/Details.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoList/Views/ToDoes/Edit.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoes/Index.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Index";
}

<h2>My ToDo List</h2>

<div id="tableDiv"></div>

<div id="todoCreateFrom">
    @using (Ajax.BeginForm("AJAXCreate", "ToDoes", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv"
    }))
    {
    <div class="form-group">
        @Html.AntiForgeryToken()
        <div>
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    }
</div>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Custom_Scripts/BuildTable.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoes/_ToDoTable.cshtml
@model IEnumerable<ToDoList.Models.ToDo>

<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

<script>
    $(document).ready(function () {
        $("#sortable").sortable({
            update: function (event, ui) {
                var itemIds = "";
                $("#sortable").find(".taskSingleInline").each(function () {
                    var itemId = $(this).attr("data-taskid")
                    itemIds = itemIds + itemId + ",";
                });
                $.ajax({
                    url: '@Url.Action("UpdateItem","ToDoes")',
                    data: { itemIds: itemIds },
                    type: 'POST',
                    success: function (data) {

                    },
                    error: function (xhr, status, error) {

                    }
                });
            }
        });
    });
</script>
<style>
    #sortable tr:hover{
        background-color:#0094ff;
        color:#fff;
    }
</style>

<div id="progressBarToDo">
    <div class="progress">
        <div class="progress-bar" role="progressbar"
             style="width:@(Html.AttributeEncode(ViewBag.Percent))%"><p>@(ViewBag.Percent)% COMPLETED</p></div>
        </div>
    </div>

    </div>

<div class="container">
    <div class="col-md-9">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation"><a href="#ToDoList" aria-controls="ToDoList" role="tab" data-toggle="tab">ToDoList</a></li>
            <li role="presentation" class="active"><a href="#DoingList" aria-controls="DoingList" role="tab" data-toggle="tab">DoingList</a></li>
            <li role="presentation"><a href="#DoneList" aria-controls="DoneList" role="tab" data-toggle="tab">DoneList</a></li>
        </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane" id="ToDoList">

                <table class="table table-bordered">
                    <tbody id="sortable" style="cursor:pointer;">


                        @foreach (var item in Model.OrderBy(o => o.RowNo))
                        {
                            if (item.IsAdmin)
                            {
                                if (!item.IsDone1 && !item.IsDone2)
                                {
                                    <tr>
                                        <td class="taskSingleInline" id="task@(item.Id)" data-taskid="@(item.Id)">
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td>
                                            @Html.CheckBoxFor(modelItem => item.IsDone, new { id = item.Id, @class = "ActiveCheck" }) Todo?
                                            @Html.CheckBoxFor(modelItem => item.IsDone1, new { id = item.Id, @class = "ActiveCheck1" }) Doing!
                                            @Html.CheckBoxFor(modelItem => item.IsDone2, new { id = item.Id, @class = "ActiveCheck2" }) Done.
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                }
                            }

                        }

                    </tbody>
                </table>
            </div>

            <div role="tabpanel" class="tab-pane active" id="DoingList">
                <table class="table table-bordered">
                    <tbody id="sortable" style="cursor:pointer;">

                        @foreach (var item in Model.OrderBy(o => o.RowNo))
                        {
                            if (!item.IsDone2 && item.IsDone1)
                            {
                                <tr>
                                    <td class="taskSingleInline" id="task@(item.Id)" data-taskid="@(item.Id)">
                                        <div class="Doings">@Html.DisplayFor(modelItem => item.Description)</div>

                                    </td>
                                    <td>
                                        @Html.CheckBoxFor(modelItem => item.IsDone, new { id = item.Id, @class = "ActiveCheck" }) Todo?
                                        @Html.CheckBoxFor(modelItem => item.IsDone1, new { id = item.Id, @class = "ActiveCheck1" }) Doing!
                                        @Html.CheckBoxFor(modelItem => item.IsDone2, new { id = item.Id, @class = "ActiveCheck2" }) Done.
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>

            <div role="tabpanel" class="tab-pane" id="DoneList">
                <table class="table table-bordered">
                    <tbody id="sortable" style="cursor:pointer;">

                        @foreach (var item in Model.OrderBy(o => o.RowNo))
                        {
                            if (item.IsDone2)
                            {
                                <tr>
                                    <td class="taskSingleInline" id="task@(item.Id)" data-taskid="@(item.Id)">
                                        <div class="CompletedToDo">@Html.DisplayFor(modelItem => item.Description)</div>

                                    </td>
                                    <td>
                                        @Html.CheckBoxFor(modelItem => item.IsDone, new { id = item.Id, @class = "ActiveCheck" }) ToDo?
                                        @Html.CheckBoxFor(modelItem => item.IsDone1, new { id = item.Id, @class = "ActiveCheck1" }) Doing!
                                        @Html.CheckBoxFor(modelItem => item.IsDone2, new { id = item.Id, @class = "ActiveCheck2" }) Done.
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <script src="~/Custom_Scripts/AddCheckBoxListener.js"></script>
    <script src="~/Custom_Scripts/AddCheckBoxListener1.js"></script>
    <script src="~/Custom_Scripts/AddCheckBoxListener2.js"></script>